version: '3.9'

services:
  frontend:
    image: sermalenk/skypro-front:lesson-35
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"

  api:
    build:
      context: .
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env_docker
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully


  migrations:
    build:
      context: .
    env_file:
      - .env_docker
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate"

  db:
    image: postgres:14.5-alpine
    restart: always
    env_file:
      - .env_docker
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      timeout: 5s
      interval: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data



volumes:
  db_data: