# Generated by Django 4.0.1 on 2022-12-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_alter_goalcategory_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalcomment',
            name='text',
            field=models.TextField(max_length=350, verbose_name='Комментарий'),
        ),
    ]
